default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: live-voting_development

test:
  <<: *default
  database: live-voting_test

production:
  <<: *default
  database: live-voting_production
  username: live-voting
  password: <%= ENV['LIVE-VOTING_DATABASE_PASSWORD'] %>
